### ISSUE TITLE
Rhino detachment Pintle weapon error when add 4+ rhinos

### ISSUE THREAD

**Issue by silencioso** [th3proj3ct/LegionsImperialis#1]
When adding additional rhinos (Space marine Demi Company > Transport > Rhino Deatachment) apears "Must have 1 more selection from Pintle Weapon (minimum 4)" when adding more than 3 rhinos, and you must select all the different Pintle Weapon options, there is no way of select the same Pintle Weapon for all the models

**Comment by th3proj3ct** [comment]
Should be corrected now, let me know if it works with V3 of marines
